---

# Attempt to install via packaged download first if preferred.
# ------------------------------------------------------------------------------

- block:
    - name: Prepare install path
      file:
        path: "{{ drush_install_path }}"
        state: directory

    - name: Check if requested Drush package file exists for download
      uri:
        url: https://github.com/drush-ops/drush/releases/download/{{ drush_version }}/drush.phar
        follow_redirects: none
        status_code: 302
      no_log: true
      become: false

    - name: Download packaged Drush release
      get_url:
        url: https://github.com/drush-ops/drush/releases/download/{{ drush_version }}/drush.phar
        dest: "{{ drush_install_path }}/drush"
        mode: "a+x"
      register: phar_download

    - name: Create drush symlink
      file:
        src: "{{ drush_install_path }}/drush"
        dest: "{{ drush_path }}"
        state: link
      when: not phar_download.skipped|default(false)

    - name: Register phar install success
      set_fact: drush_phar_installed=true
  rescue:
    - name: Register phar install failure
      set_fact: drush_phar_installed=false
  when: drush_prefer_packaged_download
  become: true


# Install via Composer if a packaged download didn't exist or is not preferred.
# ------------------------------------------------------------------------------

- include: global_drush_via_composer.yml
  when: not (drush_prefer_packaged_download and drush_phar_installed)
  become: true
